replicaCount: 1

image:
  app:
    repository: ghcr.io/robinvdveer/really-bad-chess-web-app
    tag: latest
    pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  fsGroup: 101

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 32080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: really-bad-chess.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
